name: FTX Spot Margin Leading Update 

on:
  # push 到 master 分支時會觸發
  #push:
  #  branches:
  #  - master
  # 排程每每小時觸發
  # 語法可上 crontab.guru 查詢
  schedule:
  - cron: 0 * * * *

env:
  DOTNET_VERSION: '5.0'              # set this to the dotnet version to use

jobs:
  build:
    name: Set up environment
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      env:
        # 取得在 Secrets 所設定的加密變數
        FTX_SECRET: ${{ secrets.FTX_SECRET }}
        FTX_KEY: ${{ secrets.FTX_KEY }}
      run: |
        dotnet run