name: FTX Spot Margin Leading Update 

on:
  # push 到 main 分支時會觸發
  push:
   branches:
   - main
  # 排程每每小時觸發
  # 語法可上 crontab.guru 查詢
  schedule:
  - cron: 0 * * * *

env:
  DOTNET_VERSION: '5.0'              # set this to the dotnet version to use

jobs:
  build:
    name: FTX Spot Margin Leading Update
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      env:
        # 取得在 Secrets 所設定的加密變數
        FTX_SECRET: ${{ secrets.FTX_SECRET }}
        FTX_KEY: ${{ secrets.FTX_KEY }}
      run: |-
        dotnet build  ./FTX.SDK/FTX.Console/FTXConsole.csproj -c Release -o ./app/build
        dotnet publish ./FTX.SDK/FTX.Console/FTXConsole.csproj -c Release -o ./app/publish
        # dotnet ./app/publish/FTXConsole.dll
        dotnet ./app/publish/FTXConsole.dll USD ${{ secrets.FTX_Client }}
